version: "3"

services:
  restproducer:
    container_name: restproducer_app
    build:
      context: ./app
      dockerfile: ./Dockerfile
    entrypoint: /opt/spring-cloud/bin/waitfordb.sh
    depends_on:
      - db
    ports:
      - 8080:8083
      - 5505:5505
    environment:
      MYSQL_URL: jdbc:mysql://db:3306/butola

  db:
    container_name: db
    build:
      context: .
      dockerfile: ./data/Dockerfile
    ports:
      - 3306:3306



