spring:
  application:
    name: restproducer
  datasource:
    url: jdbc:mysql://localhost:3306/restproducerdb
    username: producer
    password: producer
    driver: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect