server.port: 8083

spring:
  application:
    name: restproducer
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:playbook;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: playbook
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    show-sql: true
  hibernate:
    ddl-auto: update
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
  properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect






