server.port: 8083

spring:
  application:
    name: restproducer
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/butola
    username: dbuser
    password: dbpassword
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    show-sql: true
  hibernate:
    ddl-auto: update
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
  properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml


